### ISSUE TITLE
method Node.saveThisNodeOnly works only with backend='cassiopee'

### ISSUE THREAD

**Issue by Thomas-Bontemps** [Luispain/treelab#8] opened 2024-06-18 13:33 UTC
With the default value backend='h5py2cgns', this method does not return an error, but the file is not modified.

**Comment by Luispain** [comment] 2024-06-21 09:12
Hi !

Please provide some additional information, since I am not sure to be able to reproduce your problem. 
Trying to reproduce your issue, I encountered (and just fixed in master) a problem when using saveThisNodeOnly using :

```python
    t = cgns.Tree()
    n = cgns.Node(Name='testNode',Value=np.array([0]))
    n.attachTo(t)
    t.save('test.cgns',backend='h5py2cgns')
    n_value = n.value()
    n_value += 1
    n.saveThisNodeOnly('test.cgns',backend='h5py2cgns')
    t_updated = cgns.load('test.cgns')
    os.unlink('test.cgns')
    n_value_updated = t_updated.get('testNode').value()
    assert n_value[0] == n_value_updated[0]
```

I had an issue when saving individual node, due to an attempt of an inneccessary resizing for numerical arrays (since we do not use chunks anymore for numerical arrays -> they must have always the same size).

I've corrected that, and the aforementioned code runs ok, but still I am not sure that if this fixes your issue (since the issue I encountered produced an error, and you say you did not have any error).

May you provide a small bit of code reproducing your issue please ?

Thanks in advance !

Luis

**Comment by Thomas-Bontemps** [comment] 2024-06-21 10:07
Hi Luis, 

Here is a small example reproducing the problem:
```python
import os
import numpy as np
from treelab import cgns

t = cgns.Tree()
p = cgns.Node(Name='Parent', Parent=t) # it works if this line is commented
n = cgns.Node(Name='testNode', Value=np.array([0]), Parent=p)
t.save('test.cgns', backend='h5py2cgns')

n = cgns.load_from_path('test.cgns', 'Parent/testNode')  # it works if this line is commented
n_value = n.value()
n_value += 1
n.saveThisNodeOnly('test.cgns', backend='h5py2cgns')

t_updated = cgns.load('test.cgns')
os.unlink('test.cgns')
n_value_updated = t_updated.get('testNode').value()
print(n_value[0], n_value_updated[0])
assert n_value[0] == n_value_updated[0]
```
If I comment the line with `cgns.load_from_path`, it works. If I remove the 'Parent' node, and put 'testNode' as a direct child of the Tree `t`, it also works fine.

You may notice that this example does not work with `backend='cassiopee'`. But the following, where this is the Parent node that is loaded, works with `backend='cassiopee'` and not with `backend='h5py2cgns'`:
```python
import os
import numpy as np
from treelab import cgns

t = cgns.Tree()
p = cgns.Node(Name='Parent', Parent=t)
n = cgns.Node(Name='testNode', Value=np.array([0]), Parent=p)
t.save('test.cgns', backend='h5py2cgns')

p = cgns.load_from_path('test.cgns', 'Parent')
n = p.get(Name='testNode')
n_value = n.value()
n_value += 1
p.saveThisNodeOnly('test.cgns', backend='h5py2cgns')  # it works with backend='cassiopee'

t_updated = cgns.load('test.cgns')
os.unlink('test.cgns')
n_value_updated = t_updated.get('testNode').value()
print(n_value[0], n_value_updated[0])
assert n_value[0] == n_value_updated[0]
```
Do you have any idea ? 

Thanks,
Thomas

**Comment by Luispain** [comment] 2024-06-21 14:23
ok, thank you Thomas for this snippet of code.

I found a **parent** ↔️  **child** issue in `castNode` that impacted (among others) the operation `load_from_path` followed by a `saveThisNodeOnly`. It is now corrected.

However, your snippet of code had a small mistake (I think): I suppose you want to update Parent/testNode value, not Parent value. For this, you have to save `Parent/testNode`, as follows:

```python
    t = cgns.Tree()
    p = cgns.Node(Name='Parent', Parent=t)
    n = cgns.Node(Name='testNode', Value=np.array([0]), Parent=p)
    t.save('test.cgns', backend='h5py2cgns')

    p = cgns.load_from_path('test.cgns', 'Parent')

    n2 = p.get(Name='testNode')
    n_value = n2.value()
    n_value += 1
    n2.saveThisNodeOnly('test.cgns', backend='h5py2cgns') 

    t_updated = cgns.load('test.cgns')
    os.unlink('test.cgns')
    n_value_updated = t_updated.get('testNode').value()
    print(n_value[0], n_value_updated[0])
    assert n_value[0] == n_value_updated[0]
``` 

let me know if this solves your issue.

Thank you again !

**Comment by Thomas-Bontemps** [comment] 2024-06-21 14:44
Thank you Luis for this dev.

Well, ok this script works, but sometimes one may want to save a node **and** all its children. Maybe it should be done by another function, but it is the behavior of the current function with the backend 'cassiopee', and the behavior I was expecting.

Moreover, it seems to have other side effects that I can observe on another program using treelab. I have to check that.

**Comment by Luispain** [comment] 2024-06-21 15:24
I understand Thomas, once you have confirmed that the bug is solved, I propose to close this Issue and open a new one for asking for a recursive option for the function (or totally new function, because `saveThisNodeOnly` can be misleading if it also saves its children)

**Comment by Thomas-Bontemps** [comment] 2024-07-15 11:49
Ok, I agree, let's do this

**Closed** 2024-07-15 15:26 UTC
